# Generated by Django 2.1.3 on 2018-11-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicLocation', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryNo', models.IntegerField()),
                ('weight', models.FloatField()),
                ('datetime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemNo', models.IntegerField()),
                ('weight', models.FloatField()),
                ('description', models.CharField(max_length=2000)),
                ('qty_avail', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('IV', 'IV Fluids'), ('IV', 'IV Fluids')], default='IV', max_length=200)),
                ('profile_image', models.ImageField(default='gallery', upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Asoc_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemNo', models.IntegerField()),
                ('orderNo', models.IntegerField()),
                ('qty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.IntegerField()),
                ('priority', models.CharField(choices=[('U', 'High'), ('I', 'Medium'), ('L', 'Low')], default='U', max_length=200)),
                ('orderStatus', models.CharField(choices=[('QFP', 'Queued for Processing'), ('PBW', 'Processing by Warehouse'), ('QFD', 'Queued for Dispatch'), ('DIS', 'Dispatched'), ('DEL', 'Delivered')], default='QFP', max_length=200)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('datetime', models.DateField(blank=True, null=True)),
                ('noOfItems', models.IntegerField(blank=True, null=True)),
                ('orderType', models.CharField(choices=[('N', 'New'), ('D', 'Dequeued')], default='N', max_length=200)),
                ('clinicManager_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.ClinicLocation')),
                ('deliveryNo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('emailID', models.EmailField(max_length=254)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.ClinicLocation')),
            ],
        ),
    ]
