# Generated by Django 2.1.2 on 2018-11-05 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('clinicLocation', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryNo', models.IntegerField()),
                ('weight', models.FloatField()),
                ('datetime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemNo', models.IntegerField()),
                ('weight', models.FloatField()),
                ('description', models.CharField(max_length=2000)),
                ('qty_avail', models.IntegerField()),
                ('category', models.CharField(choices=[('IV', 'IV Fluids'), ('IV', 'IV Fluids')], default='IV', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.IntegerField()),
                ('priority', models.CharField(choices=[('U', 'Urgent'), ('I', 'Intermediate'), ('L', 'Low')], default='U', max_length=200)),
                ('orderStatus', models.CharField(choices=[('QFP', 'Queued for Processing'), ('PBW', 'Processing by Warehouse'), ('QFD', 'Queued for Dispatch'), ('DIS', 'Dispatched'), ('DEL', 'Delivered')], default='QFP', max_length=200)),
                ('weight', models.FloatField()),
                ('datetime', models.DateField()),
                ('clinicManager_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.ClinicManager')),
                ('deliveryNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Delivery')),
            ],
        ),
    ]
