# Generated by Django 2.1.2 on 2018-11-05 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
