# Generated by Django 2.1.2 on 2018-11-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinicAsocclinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicID1', models.IntegerField()),
                ('clinicID2', models.IntegerField()),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='cliniclocation',
            name='clinicID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
