# Generated by Django 2.1.2 on 2018-11-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20181119_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clinicAsocclinic',
        ),
        migrations.RemoveField(
            model_name='cliniclocation',
            name='clinicID',
        ),
    ]
