# Generated by Django 2.1.3 on 2018-11-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20181119_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
