# Generated by Django 2.1.2 on 2018-11-07 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='clinicManager_location1',
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
