# Generated by Django 2.1.2 on 2018-11-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20181107_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('U', 'High'), ('I', 'Medium'), ('L', 'Low')], default='U', max_length=200),
        ),
    ]
