# Generated by Django 2.1.2 on 2018-11-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20181107_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='profile_image',
            field=models.ImageField(default='gallery', upload_to='gallery'),
        ),
    ]
