# Generated by Django 2.1.2 on 2018-11-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20181113_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_asoc_order',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
