# Generated by Django 2.1.3 on 2018-11-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_order_ordertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.ClinicLocation')),
            ],
        ),
        migrations.RemoveField(
            model_name='clinicmanager',
            name='clinicLocation',
        ),
        migrations.DeleteModel(
            name='ClinicManager',
        ),
    ]
