# Generated by Django 2.1.3 on 2018-11-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_order_ordertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('emailID', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='clinicmanager',
            name='clinicLocation',
        ),
        migrations.DeleteModel(
            name='ClinicManager',
        ),
    ]
