# Generated by Django 2.1.2 on 2018-11-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_auto_20181115_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
