# Generated by Django 2.1.2 on 2018-11-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_auto_20181115_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Asoc_Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.IntegerField()),
                ('deliveryNo', models.IntegerField()),
            ],
        ),
    ]
