# Generated by Django 2.1.2 on 2018-11-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_cliniclocation_clinicid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniclocation',
            name='clinicID',
            field=models.IntegerField(),
        ),
    ]
