# Generated by Django 2.1.2 on 2018-11-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_clinic_asoc_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedvalues',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
