# Generated by Django 2.1.2 on 2018-11-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_storedvalues_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, default='Shiven', max_length=200, null=True),
        ),
    ]
