# Generated by Django 2.1.2 on 2018-11-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_order_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('QFP', 'Queued for Processing'), ('PBW', 'Processing by Warehouse'), ('QFD', 'Queued for Dispatch'), ('QFD2', 'Queued for Dispatch2'), ('DIS', 'Dispatched'), ('DEL', 'Delivered')], default='QFP', max_length=200),
        ),
    ]
