# Generated by Django 2.1.2 on 2018-11-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='profile_image',
            field=models.ImageField(default='Users/anujkapur/Documents/GitHub/Dromed/config/db/benadryl.png', upload_to='Users/anujkapur/Documents/GitHub/Dromed/config/db'),
        ),
    ]
