# Generated by Django 2.1.2 on 2018-11-07 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20181107_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicLocation', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='clinicmanager',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='clinicmanager',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='clinicmanager',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='clinicManager_username',
        ),
        migrations.AlterField(
            model_name='clinicmanager',
            name='clinicLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.ClinicLocation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.Delivery'),
        ),
        migrations.AddField(
            model_name='order',
            name='clinicManager_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.ClinicLocation'),
        ),
    ]
