# Generated by Django 2.1.2 on 2018-11-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20181107_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='profile_image',
            field=models.ImageField(default='config/db', upload_to='config/db'),
        ),
    ]
