# Generated by Django 2.1.2 on 2018-11-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20181107_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Asoc_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='item_asoc_order',
            name='orderNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Order'),
        ),
    ]
