# Generated by Django 2.1.2 on 2018-11-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20181113_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='noOfItems',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
