# Generated by Django 2.1.2 on 2018-11-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_order_ordertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='noOfOrders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=200),
        ),
    ]
