# Generated by Django 2.1.2 on 2018-11-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_order_asoc_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
