# Generated by Django 2.1.2 on 2018-11-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_auto_20181119_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qty_avail',
        ),
    ]
