# Generated by Django 2.1.2 on 2018-11-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_remove_item_qty_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qty_avail',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
