# Generated by Django 2.1.2 on 2018-11-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_item_qty_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclocation',
            name='clinicID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
