# Generated by Django 2.1.2 on 2018-12-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_auto_20181130_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='datetime',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
