# Generated by Django 2.1.2 on 2018-12-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_auto_20181201_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_string',
            field=models.CharField(default='N', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='time_string',
            field=models.CharField(default='N', max_length=200),
        ),
    ]
