# Generated by Django 2.1.2 on 2018-12-01 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_auto_20181201_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_string',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_string',
        ),
    ]
