# Generated by Django 2.1.2 on 2018-12-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_auto_20181201_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('QFP', 'Queued for Processing'), ('PBW', 'Processing by Warehouse'), ('QFD', 'Queued for Dispatch'), ('QFD2', 'Queued for Dispatch2'), ('DIS', 'Dispatched'), ('DEL', 'Delivered'), ('CAN', 'Cancelled')], default='CAN', max_length=200),
        ),
    ]
